/* Generated by Cython 0.23.1 */

#ifndef __PYX_HAVE__MawCluster__BCFastq
#define __PYX_HAVE__MawCluster__BCFastq


#ifndef __PYX_HAVE_API__MawCluster__BCFastq

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_10MawCluster_7BCFastq_Num2NucDict;
__PYX_EXTERN_C DL_IMPORT(__pyx_t_10MawCluster_7BCFastq_py_array) __pyx_v_10MawCluster_7BCFastq_nucs;
__PYX_EXTERN_C DL_IMPORT(__pyx_t_10MawCluster_7BCFastq_cystr) __pyx_v_10MawCluster_7BCFastq_REMOVE_NS;

#endif /* !__PYX_HAVE_API__MawCluster__BCFastq */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initBCFastq(void);
#else
PyMODINIT_FUNC PyInit_BCFastq(void);
#endif

#endif /* !__PYX_HAVE__MawCluster__BCFastq */
