/* Generated by Cython 0.23.1 */

#ifndef __PYX_HAVE__analyscripts__Schismatic
#define __PYX_HAVE__analyscripts__Schismatic


#ifndef __PYX_HAVE_API__analyscripts__Schismatic

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_12analyscripts_10Schismatic_int2nuc;

#endif /* !__PYX_HAVE_API__analyscripts__Schismatic */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initSchismatic(void);
#else
PyMODINIT_FUNC PyInit_Schismatic(void);
#endif

#endif /* !__PYX_HAVE__analyscripts__Schismatic */
