#!/bin/sh
#Includes all steps to convert HiSeq file structure into fastq files


########################################
#NOW ALL IN (almost) ONE EASY STEP!!!!!!!!!!!!!!
########################################

# First from a terminal go to the /Data/Intensities/BaseCalls/ directory of the raw data directory for the flow cell you want to process
# Make sure that a SampleSheet.csv exists in this directory
# Then paste the following command and hit enter

/illumina/software/CASAVA-1.8.0/bin/configureBclToFastq.pl --input-dir ./ --output-dir ../../../Unaligned --sample-sheet ./SampleSheet.csv --fastq-cluster-count 100000000 --ignore-missing-stats --ignore-missing-bcl


#another example
/illumina/software/CASAVA-1.8.0/bin/configureBclToFastq.pl --input-dir Data/Intensities/BaseCalls/ --output-dir /media/fastq_1/FASTQ_120118_SN573_0100_AC0DWRACXX --sample-sheet C0DWRACXX_SampleSheet.csv --fastq-cluster-count 1000000000 --ignore-missing-stats --ignore-missing-bcl

#here is the same example as above but using CASAVA version 1.8.2
#/usr/local/CASAVA-1.8.2/bin/configureBclToFastq.pl --input-dir Data/Intensities/BaseCalls/ --output-dir /media/fastq_1/FASTQ_120118_SN573_0100_AC0DWRACXX --sample-sheet C0DWRACXX_SampleSheet.csv --fastq-cluster-count 1000000000 --ignore-missing-stats --ignore-missing-bcl

#TO LIMIT WHICH LANES AND TILES FROM THE SAMPLESHEET TO CONVERT TO FASTQ
#EITHER
#1 make two different sample sheets, in which case you can limit which lanes but you cannot limit which flow-cell tiles are converted to fastq
#2 use the --tiles option
#	--tiles option takes a comma-separated list of
#	regular expressions to match against the
#	expected "s_<lane>_<tile>" pattern, where
#	<lane> is the lane number (1-8) and <tile> is
#	the 4 digit tile number (left-padded with 0s).
#
# EXAMPLE
# --tiles=s_[2468]_[0-9][0-9][02468]5,s_1_0001

#an example when you have indexes but do not want to demultiplex yet (you get read1, index read and read2) the added parameter is --use-bases-mask
#For this to work, the SampleSheet.csv will need to reflect no more than one sample per lane and no indexes listed.
/illumina/software/CASAVA-1.8.0/bin/configureBclToFastq.pl --input-dir Data/Intensities/BaseCalls/ --output-dir /media/fastq_1/FASTQ_120118_SN573_0100_AC0DWRACXX --sample-sheet C0DWRACXX_SampleSheet.csv --fastq-cluster-count 1000000000 --ignore-missing-stats --ignore-missing-bcl --use-bases-mask Y101,Y7,Y101

#@author daniel comments/command
#For taking advantage of the secondary index for BMFTools
/illumina/software/CASAVA-1.8.0/bin/configureBclToFastq.pl --input-dir Data/Intensities/BaseCalls/ --output-dir /media/fastq_1/FASTQ_120118_SN573_0100_AC0DWRACXX --sample-sheet C0DWRACXX_SampleSheet.csv --fastq-cluster-count 1000000000 --ignore-missing-stats --ignore-missing-bcl --use-bases-mask Y65N,I6N,Y24N,Y65N
#On sample sheet: Change chemistry to "Default"
#And delete the "24N".
#For index 2, remove the Ns

#Example of SampleSheet.csv format
FCID,Lane,SampleID,SampleRef,Index,Description,Control,Recipe,Operator,SampleProject
D0ND8ACXX,1,NC07,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,2,NC07,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,3,NC07,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,4,NC07,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,5,NC41,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,6,NC41,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,7,NC41,Human,,humangenome,N,,KM,humangenome
D0ND8ACXX,8,NC41,Human,,humangenome,N,,KM,humangenome
###############################################################################
###############################################################################








###############################################################################
#Here are options for the above command

#Set up then "make" the script files to build Qseq files
#make command automatically creates the Qseq files

#This has been modified
#Now uses setupBclToQseq from the Offline Base Caller software!!!!!!

#setupBclToQseq.py---
#Script to setup the output directory for the conversion of BCLfiles produced by
#RTA into a standard QSEQ-based base calls folder.

#Options:
#  -h, --help            show this help message and exit
#  -i INPUT_DIRECTORY, --input-directory=INPUT_DIRECTORY
#                        Full path to the input directory containing the 'lane'
#                        directories and ultimately the bcl files
#  -b BASE_CALLS_DIRECTORY, --base-calls-directory=BASE_CALLS_DIRECTORY
#                        Full path to the Base Calls directory generated by the
#                        instrument if different from the input directory
#  -o OUTPUT_DIRECTORY, --output-directory=OUTPUT_DIRECTORY
#                       Full path to the output directory
#  -f FILTER_DIRECTORY, --filter-directory=FILTER_DIRECTORY
#                        Full path to the filter directory if different from
#                        the input directory
#  -p POSITIONS_DIRECTORY, --positions-directory=POSITIONS_DIRECTORY
#                        Full path to the positions directory if dirrerent from
#                        the filter directory
#  --in-place            Allow in-place conversion
#  --overwrite           Overwrite the content of the output directory if it
#                        already exists
#  --GERALD=GERALD       Path to the GERALD config file
#  -S, --silent          Do not produce any information or warnings.
#  -Q, --quiet           Produce only warnings. Skips general information.
#  -V, --verbose         Produce additional debug information.
#  -v, --version         Print the version informatio and exits
#  -L LOG_FILE, --log-file=LOG_FILE
#                        Full path to the log file






# Next move to the output directory
cd ../../../Unaligned

# Next run the make file with all cores (-j 16)
make -j 16



###############################################################################
#Step 2 demultiplex qseq (via Casava from Illumina)

