# IPython log file

get_ipython().magic(u'pinfo dir')
import BCVCF
BCVCF.fixVCF 
get_ipython().system(u' ls')
BCVCF.ParseVCF 
BCVCF.ParseVCF()
get_ipython().magic(u'pinfo BCVCF.ParseVCF')
get_ipython().system(u'ls')
NA12878GenomeVCF = BCVCF.ParseVCF('40K.vcf')
NA12878GenomeVCF.Records[0]
get_ipython().magic(u'pinfo dir')
get_ipython().magic(u'pinfo collections')
get_ipython().show_usage()
get_ipython().magic(u'magic')
get_ipython().show_usage()
get_ipython().magic(u'pinfo2 magic')
lt
get_ipython().magic(u'pinfo subprocess.PIPE')
import subprocess
get_ipython().magic(u'pinfo subprocess.PIPE')
get_ipython().magic(u'magic')
get_ipython().magic(u'alias')
get_ipython().show_usage()
lt
which
get_ipython().system(u' ls -p')
get_ipython().system(u' ls -lah')
get_ipython().system(u' ls -lah | sort -k2,2n')
get_ipython().system(u' cat BCVCF.py')
get_ipython().show_usage()
get_ipython().magic(u'cd')
get_ipython().system(u' ls')
get_ipython().magic(u'cd /yggdrasil/workspace/BMFTools/')
get_ipython().system(u' ls')
get_ipython().magic(u'cd Scripts/')
get_ipython().system(u' ls')
get_ipython().magic(u'help')
get_ipython().magic(u'who_ls')
get_ipython().magic(u'who')
get_ipython().magic(u'whos')
get_ipython().magic(u'recall')
['BCVCF', 'NA12878GenomeVCF', 'subprocess']
get_ipython().magic(u'rep')
get_ipython().magic(u'run')
get_ipython().magic(u'ldir')
get_ipython().magic(u'latex')
get_ipython().magic(u'logstart')
get_ipython().magic(u'lsmagic')
get_ipython().magic(u'xdel')
get_ipython().magic(u'lk')
get_ipython().magic(u'pinfo %lk')
get_ipython().magic(u'lx')
get_ipython().magic(u'la')
get_ipython().magic(u'ls')
get_ipython().magic(u'ld')
get_ipython().magic(u'gcc')
get_ipython().magic(u'pinfo ')
get_ipython().system(u'?')
get_ipython().system(u'cnf')
get_ipython().system(u' echo "ECHO"')
