"""Creates a heatmap from the ErrorArray generated by EMG/ErrMer"""

import numpy as np
import matplotlib.pyplot as plt
import csv
import matplotlib

font = {'family' : 'normal',
        'weight' : 'normal',
        'size'   : 22}

matplotlib.rc('font', **font)


r1data = []
r2data = []
with open("S370x1_3D.errArr.out.out") as t:
    for line in csv.reader(t, delimiter="|"):
        r1 = line[0]
        r2 = line[1]
        r1quals = []
        r2quals = []
        for qual1 in r1.split(','):
            bases = []
            for base in qual1.split(':'):
                bases.append(np.float64(base))
            r1quals.append(np.mean(bases))
        r1data.append(r1quals)
        for qual2 in r2.split(","):
            bases = []
            for base in qual2.split(':'):
                bases.append(np.float64(base))
            r2quals.append(np.mean(bases))
        r2data.append(r2quals)
r1data = np.array(r1data)
r2data = np.array(r2data)

fig, ax = plt.subplots(figsize=(15,10))
plt.suptitle("Observed Quality by Illumina Quality and Cycle (Read 2)")
heatmap = ax.pcolormesh(np.transpose(r2data), cmap=plt.cm.Reds)
cbar = fig.colorbar(heatmap, label="Observed Quality")
ax.axis('tight')
plt.xlabel("Cycle (Position in Read)")
plt.ylabel("Illumina Given Quality Score")
plt.savefig("CycleQualityHeatmapRead2.png")
plt.show()
