"""Creates a heatmap from the ErrorArray generated by EMG/ErrMer"""

import numpy as np
import matplotlib.pyplot as plt
import csv
import matplotlib

font = {'family' : 'normal',
        'weight' : 'normal',
        'size'   : 22}

matplotlib.rc('font', **font)

r1data = []
r2data = []
with open("S370x1_2D.errArr.out.out") as t:
    for line in csv.reader(t, delimiter="|"):
        r1 = line[0]
        r2 = line[1]
        r1bases = []
        for base in r1.split(','):
            r1bases.append(np.float64(base))
        r1data.append(r1bases)
        r2bases = []
        for base in r2.split(','):
            r2bases.append(np.float64(base))
        r2data.append(r2bases)

r1data = np.array(r1data)
r2data = np.array(r2data)

fig, ax = plt.subplots(figsize=(15,10))
plt.suptitle("Observed Quality by Cycle and Nucleotide (Read 1)")
heatmap = ax.pcolormesh(np.transpose(r1data), cmap=plt.cm.Blues)
cbar = fig.colorbar(heatmap, label="Observed Quality")
ax.axis('tight')
ax.set_yticks([0.5, 1.5, 2.5, 3.5])
ax.set_yticklabels(["A","C","G","T"])
plt.xlabel("Cycle (Position in Read)")
plt.ylabel("Nucleotide")
plt.savefig("ErrorArrayHeatmapRead1.png")
plt.show()
