/* Generated by Cython 0.23.1 */

#ifndef __PYX_HAVE__utilBMF__cstring
#define __PYX_HAVE__utilBMF__cstring


#ifndef __PYX_HAVE_API__utilBMF__cstring

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(__pyx_t_7utilBMF_7cstring_cystr) __pyx_v_7utilBMF_7cstring_PH2CHR_TRANS;

#endif /* !__PYX_HAVE_API__utilBMF__cstring */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcstring(void);
#else
PyMODINIT_FUNC PyInit_cstring(void);
#endif

#endif /* !__PYX_HAVE__utilBMF__cstring */
