/* Generated by Cython 0.23.1 */

#ifndef __PYX_HAVE__utilBMF__HTSUtils
#define __PYX_HAVE__utilBMF__HTSUtils


#ifndef __PYX_HAVE_API__utilBMF__HTSUtils

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(__pyx_t_7utilBMF_7cstring_cystr) __pyx_f_7utilBMF_8HTSUtils_RevCmp(__pyx_t_7utilBMF_7cstring_cystr, int __pyx_skip_dispatch);
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_f_7utilBMF_8HTSUtils_permuteNucleotides(long, int __pyx_skip_dispatch, struct __pyx_opt_args_7utilBMF_8HTSUtils_permuteNucleotides *__pyx_optional_args);
__PYX_EXTERN_C DL_IMPORT(__pyx_t_7utilBMF_7cstring_cystr) __pyx_f_7utilBMF_8HTSUtils_cGetBS(__pyx_t_7utilBMF_8HTSUtils_pFastqProxy_t);

__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_PysamToChrDict;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_ph2chrDict;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_TypeConversionDict;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_chr2ph;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_chr2phStr;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_int2Str;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_TagTypeDict;
__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_7utilBMF_8HTSUtils_nucList;

#endif /* !__PYX_HAVE_API__utilBMF__HTSUtils */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initHTSUtils(void);
#else
PyMODINIT_FUNC PyInit_HTSUtils(void);
#endif

#endif /* !__PYX_HAVE__utilBMF__HTSUtils */
