"samples":
    "normal": ["normal_sample"]
    "tumor": ["tumor_sample"]
"units":
    "normal_sample": ["FASTQ/normal_R1.fastq.gz", "FASTQ/normal_R2.fastq.gz"]
    "tumor_sample": ["FASTQ/tumor_R1.fastq.gz", "FASTQ/tumor_R2.fastq.gz"]
"undetermined":
    "reads": ["FASTQ/Undetermined_R1.fastq.gz", "FASTQ/Undetermined_R2.fastq.gz"]
params:
    bs_bwa: "-YCT 0"
    standard_bwa: "-T 0 -Y"
    strelka_config: "config.ini"
    threads:
        bwa: 6
        bmftools: 6
        other: 2
    max_mem: "3G"
    homing_seq: "TGACT"
    gatk: "java -jar -Xmx10G ~/bin/GenomeAnalysisTK.jar"
"platform": "Illumina"
"references":
    "Human_b37": "<Path to Reference>"
    "dbSNP": "<Path to dbSNP vcf>"
    "bed": "<Path to target bed file>"
    "phiX": "<Path to phiX reference>"
